# Permalinks
permalink:        pretty

# Setup
title:            Jeroen Bouma
description:      "An overview of all my projects and thoughts"
url:              https://jerbouma.github.io/
basurl:           "/"

author:
  name:           'Jeroen Bouma'
  url:            https://www.linkedin.com/in/boumajeroen/

paginate:         5

github:
  repo:           https://github.com/JerBouma/jerbouma.github.io