# Permalinks
permalink:        pretty

# Setup
title:            Jeroen Bouma's Portfolio
tagline:          'A Jekyll theme'
description:      'An overview of all my project and thoughts'

author:
  name:           'Jeroen Bouma'
  url:            https://www.linkedin.com/in/boumajeroen/

paginate:         5
