require "cgi"

# Gives every metric in the Finance Toolkit documentation its own page.
#
# The module pages (/projects/financetoolkit/docs/ratios and friends) are
# generated by assets/python/docs.py and hold dozens of functions each, which
# is great for browsing but means a search for "Altman Z-Score Python" can only
# ever land on one 30,000-word page about everything. This generator splits
# those module pages at build time into one page per `get_*` function, e.g.
# /projects/financetoolkit/docs/models/altman-z-score, with its own title,
# description, formula, example and links to the related metrics.
#
# Nothing is duplicated in the repository: the pages are cut from the module
# page's Markdown on every build, so rerunning docs.py updates them too. The
# human-readable names and the grouping come from the docs sidebars in
# _data/navigation.yml; a function without a sidebar entry gets no page.
#
# The module pages stay exactly as they are (their anchors are linked from the
# FinanceToolkit README), apart from a small link under each function heading
# that points to its dedicated page.
module DocsMetricPages
  DOCS_ROOT = "/projects/financetoolkit/docs".freeze

  # module key => source file; toolkit, discovery and portfolio are data
  # plumbing rather than metrics people search for, so they are left out
  MODULES = {
    "ratios"       => "Ratios",
    "models"       => "Models",
    "options"      => "Options",
    "technicals"   => "Technicals",
    "fixedincome"  => "Fixed Income",
    "risk"         => "Risk",
    "performance"  => "Performance",
    "econometrics" => "Econometrics",
    "economics"    => "Economics",
  }.freeze

  SECTION = /^## (get_\w+)\n(.*?)(?=^## |\z)/m

  # generated page paths (kept for reference by other plugins and tests)
  GENERATED = []

  class Page < Jekyll::PageWithoutAFile; end

  module_function

  def slugify(text)
    Jekyll::Utils.slugify(text.to_s.gsub("&", " and "), :mode => "default")
  end

  # anchor => { title:, group: } from the module's sidebar, plus group => [anchors]
  def sidebar(site, key)
    entries = Array(site.data.dig("navigation", "financetoolkit-docs-#{key}"))
    metrics = {}
    groups = Hash.new { |h, k| h[k] = [] }
    walk = lambda do |items, group|
      items.each do |item|
        url = item["url"].to_s
        if url.start_with?("#{DOCS_ROOT}/#{key}#get_")
          anchor = url.split("#", 2).last
          next if metrics.key?(anchor)
          metrics[anchor] = { :title => item["title"].to_s.strip, :group => group }
          groups[group] << anchor
        end
        walk.call(Array(item["children"]), item["title"].to_s.strip) if item["children"]
      end
    end
    walk.call(entries, MODULES[key])
    [metrics, groups]
  end

  # split a function section into its parts
  def parse(body)
    body = body.sub(/\n---\s*\z/, "").strip
    code_at   = body.index("```python")
    args_at   = body.index("**Args:**") || body.index("**Returns:**")
    desc_end  = [args_at, code_at, body.length].compact.min
    desc      = body[0...desc_end].strip
    args      = args_at ? body[args_at...(code_at || body.length)].sub(/\*\*As an example:\*\*\s*\z/, "").strip : ""
    example   = code_at ? body[code_at..].strip : ""
    { :description => desc, :arguments => args, :example => example }
  end

  def plain(markdown)
    markdown.gsub(/\$\$.*?\$\$/m, " ")
            .gsub(/\[([^\]]+)\]\([^)]+\)(\{:[^}]*\})?/, '\1')
            .gsub(/[*_`]/, "")
            .gsub(/\s+/, " ").strip
  end

  # First paragraph of the docstring, topped up with the next paragraphs when
  # it is a one-liner ("Calculate the Ljung-Box test for autocorrelation."),
  # and with a line about the page itself when even that stays short.
  def description_for(name, desc)
    paragraphs = desc.split(/\n\s*\n/)
                     .reject { |p| p.lstrip.start_with?("- ", "$$", "|") }
                     .map { |p| plain(p) }
                     .reject { |p| p.empty? || (p.end_with?(":") && p.length < 40) }
    text = paragraphs.shift.to_s
    text = "#{text} #{paragraphs.shift}" while text.length < 110 && !paragraphs.empty?
    text = "#{text} Formula, parameters and a Python example with the Finance Toolkit." if text.length < 110
    text = text.sub(/:\z/, ".")
    return text if text.length <= 158
    cut = text[0, 155]
    cut = cut[0, cut.rindex(" ") || cut.length].sub(/[,;:]\z/, "")
    "#{cut}..."
  end

  # The theme runs <title> through markdownify, where a bare "|" turns the
  # title into a table, so the separator is written as an entity (as the
  # theme's own title_separator is); lengths are measured with a plain "|".
  # "Altman Z-Score | Finance Toolkit". When that runs past 65 characters the
  # bracketed acronym goes first ("Forward Price to Earnings Growth Ratio
  # (Forward PEG)" loses "(Forward PEG)"), and only then the suffix.
  def seo_title_for(name)
    short = name.sub(/\s*\([^()]*\)\s*\z/, "")
    title = ["#{name} | Finance Toolkit", "#{short} | Finance Toolkit", short]
              .find { |t| t.length <= 65 } || short
    title.sub(" | ", " &#124; ")
  end

  # just the argument bullets from the Args block, without Returns/Raises/Notes
  def arguments_for(block)
    args = block[/\*\*Args:\*\*\s*(.*?)(?=\*\*(?:Returns|Raises|Notes|As an example):\*\*|\z)/m, 1].to_s.strip
    args.start_with?("- ") ? args : ""
  end

  def content_for(name, key, fn_name, anchor, parts, related, module_url)
    module_name = MODULES[key]
    out = +""
    out << parts[:description] << "\n\n"
    # for readers who would rather ask an AI assistant than write Python
    out << "**No programming experience?** With the [Finance Toolkit MCP server](/projects/financetoolkit/mcp), "
    out << "AI assistants such as Claude and ChatGPT can calculate the #{name} for you. "
    out << "Just ask in plain English.\n{: .notice--info .docs-mcp-note}\n\n"
    unless parts[:example].empty?
      out << "## Calculate the #{name} in Python\n\n"
      out << "The #{name} is available in the #{module_name} module of the open-source "
      out << "[Finance Toolkit](/projects/financetoolkit). Install it with:\n{: .docs-boilerplate}\n\n"
      out << "```python\npip install financetoolkit -U\n```\n\n"
      out << "Then call `#{fn_name}` as shown below.\n{: .docs-boilerplate}\n\n"
      out << parts[:example] << "\n\n"
    end
    arguments = arguments_for(parts[:arguments])
    unless arguments.empty?
      out << "## Parameters\n\n"
      out << "`#{fn_name}` accepts the following parameters:\n{: .docs-boilerplate}\n\n"
      out << arguments << "\n\n"
    end
    unless related.empty?
      group = related.first[:group]
      heading = if group != module_name then "Related #{group}"
                elsif module_name == "Models" then "Related Models"
                else "Related #{module_name} Metrics"
                end
      # same pill buttons as the module switcher on the docs pages
      pills = related.map do |r|
        %(<a href="#{r[:url]}" class="ft-module-pill">#{CGI.escapeHTML(r[:title])}</a>)
      end
      out << "## #{heading}\n\n"
      out << %(<div class="ft-module-switcher docs-related">\n  #{pills.join("\n  ")}\n</div>\n\n)
    end
    out << "The [#{module_name} module overview](#{module_url}##{anchor}) lists every "
    out << "function in the module.\n{: .docs-boilerplate}\n"
    out
  end

  # the first plain paragraph of a description (not a list or formula)
  def overview_summary(desc)
    desc.split(/\n\s*\n/).map(&:strip)
        .find { |p| !p.empty? && !p.start_with?("- ", "$$", "|", "**") } || ""
  end

  # up to twelve metrics from the same sidebar group, nearest to this one in
  # the sidebar order first, so neighbouring metrics link to each other
  def related_for(anchor, group_anchors, urls, limit = 12)
    list = group_anchors.select { |a| urls[a] }
    index = list.index(anchor) || 0
    (list - [anchor]).sort_by { |a| [(list.index(a) - index).abs, list.index(a)] }
                     .first(limit)
                     .sort_by { |a| list.index(a) }
  end

  # the docstring's "Also known as: PE ratio, P/E ratio, ..." names, used as
  # alternate names in the structured data
  def also_known_as(desc)
    line = desc[/\*\*Also known as:\*\*\s*(.+)/, 1].to_s
    line.sub(/\.\s*\z/, "").split(/,\s*/).map(&:strip).reject(&:empty?)
  end

  def unique_description(name, text, seen)
    unless seen.include?(text)
      seen << text
      return text
    end
    text = "#{name}: #{text}"
    text = "#{text[0, 155][0, text[0, 155].rindex(' ') || 155]}..." if text.length > 158
    seen << text
    text
  end

  def generate(site)
    seen_descriptions = []
    source_pages = site.pages.each_with_object({}) do |page, map|
      map[page.url] = page if page.url.start_with?(DOCS_ROOT)
    end

    MODULES.each_key do |key|
      module_url = "#{DOCS_ROOT}/#{key}"
      module_page = source_pages[module_url]
      next unless module_page

      metrics, groups = sidebar(site, key)
      # sidebar anchors are lowercase (kramdown's heading ids), a few function
      # names are not (get_EBT_to_EBIT), so sections are keyed by the lowercase
      # name and keep the real one for the code sample
      sections = module_page.content.scan(SECTION).to_h { |fn, body| [fn.downcase, [fn, body]] }

      urls = {}
      used = {}
      metrics.each do |anchor, info|
        next unless sections.key?(anchor)
        slug = slugify(info[:title])
        slug = "#{slug}-#{slugify(anchor.delete_prefix('get_'))}" if used[slug]
        used[slug] = true
        urls[anchor] = "#{module_url}/#{slug}"
      end

      urls.each do |anchor, url|
        info    = metrics[anchor]
        fn_name, body = sections[anchor]
        parts   = parse(body)
        # a metric alone in its sidebar group falls back to its neighbours in
        # the whole module, so every page links onwards
        pool    = groups[info[:group]].count { |a| urls[a] } > 1 ? groups[info[:group]] : metrics.keys
        group   = pool.equal?(groups[info[:group]]) ? info[:group] : MODULES[key]
        related = related_for(anchor, pool, urls).map do |a|
          { :title => metrics[a][:title], :url => urls[a], :group => group }
        end

        description = unique_description(info[:title], description_for(info[:title], parts[:description]), seen_descriptions)
        page = Page.new(site, site.source, url.delete_prefix("/").sub(%r{/[^/]+\z}, ""), "#{url.split('/').last}.md")
        page.content = content_for(info[:title], key, fn_name, anchor, parts, related, module_url)
        page.data.merge!(
          "layout"               => "single",
          "title"                => info[:title],
          "seo_title"            => seo_title_for(info[:title]),
          "seo_title_suffix"     => false,
          "description"          => description,
          "excerpt"              => description,
          "permalink"            => url,
          "classes"              => "wide-sidebar",
          "author_profile"       => false,
          "sidebar"              => { "nav" => "financetoolkit-docs-#{key}" },
          "redirect_from"        => ["#{url}/"],
          "docs_module"          => MODULES[key],
          "docs_module_url"      => module_url,
          "docs_function"        => fn_name,
          "docs_aka"             => also_known_as(parts[:description]),
          "image"                => "/assets/images/projects/FinanceToolkit.jpg",
          "share"                => true,
          "last_modified_at"     => module_page.data["last_modified_at"],
          "last_modified_at_from_git" => module_page.data["last_modified_at_from_git"]
        )
        site.pages << page
        GENERATED << page.relative_path
      end

      # The module page becomes an overview: every function with its own page
      # keeps its heading (so the anchors linked from the README keep working),
      # the first paragraph of its description and a link to the full page.
      # Functions without a page of their own (collect_*) keep their full text.
      module_page.content = module_page.content.gsub(SECTION) do
        fn, body = Regexp.last_match(1), Regexp.last_match(2)
        anchor = fn.downcase
        next Regexp.last_match(0) unless urls[anchor]
        summary = overview_summary(parse(body)[:description])
        link = %(<p class="docs-metric-link"><a href="#{urls[anchor]}">) +
               %(#{CGI.escapeHTML(metrics[anchor][:title])}: formula, example and parameters</a></p>)
        "## #{fn}\n\n#{summary}\n\n#{link}\n\n"
      end
    end
  end

  class Generator < Jekyll::Generator
    safe true
    # before jekyll-redirect-from (normal) and jekyll-sitemap (lowest), so the
    # trailing-slash redirects and the sitemap entries include these pages
    priority :high

    def generate(site)
      GENERATED.clear
      DocsMetricPages.generate(site)
    end
  end
end

# Search: the metric pages hold the full text now that the module pages are
# overviews, so they are indexed. Paragraphs that repeat on every page (the
# links to the metric pages, the install and parameter lead-ins, the MCP note)
# are skipped so they do not flood the results.
# (This site defines no other Algolia hooks; move them here if that changes.)
if defined?(Jekyll::Algolia::Hooks)
  module Jekyll
    module Algolia
      module Hooks
        SKIPPED_CLASSES = %w[docs-metric-link docs-boilerplate docs-mcp-note].freeze

        def self.before_indexing_each(record, node, _context)
          classes = node.respond_to?(:[]) ? node["class"].to_s.split : []
          return nil if (classes & SKIPPED_CLASSES).any?
          record
        end
      end
    end
  end
end
