# Gives every metric in the Finance Toolkit documentation its own page.
#
# The module pages (/projects/financetoolkit/docs/ratios and friends) are
# generated by assets/python/docs.py and hold dozens of functions each, which
# is great for browsing but means a search for "Altman Z-Score Python" can only
# ever land on one 30,000-word page about everything. This generator splits
# those module pages at build time into one page per `get_*` function, e.g.
# /projects/financetoolkit/docs/models/altman-z-score, with its own title,
# description, formula, example and links to the related metrics.
#
# Nothing is duplicated in the repository: the pages are cut from the module
# page's Markdown on every build, so rerunning docs.py updates them too. The
# human-readable names and the grouping come from the docs sidebars in
# _data/navigation.yml; a function without a sidebar entry gets no page.
#
# The module pages stay exactly as they are (their anchors are linked from the
# FinanceToolkit README), apart from a small link under each function heading
# that points to its dedicated page.
module DocsMetricPages
  DOCS_ROOT = "/projects/financetoolkit/docs".freeze

  # module key => source file; toolkit, discovery and portfolio are data
  # plumbing rather than metrics people search for, so they are left out
  MODULES = {
    "ratios"       => "Ratios",
    "models"       => "Models",
    "options"      => "Options",
    "technicals"   => "Technicals",
    "fixedincome"  => "Fixed Income",
    "risk"         => "Risk",
    "performance"  => "Performance",
    "econometrics" => "Econometrics",
    "economics"    => "Economics",
  }.freeze

  SECTION = /^## (get_\w+)\n(.*?)(?=^## |\z)/m

  # generated page paths, so the Algolia hook below can leave them out of the
  # search index (the module pages already cover the same text there)
  GENERATED = []

  class Page < Jekyll::PageWithoutAFile; end

  module_function

  def slugify(text)
    Jekyll::Utils.slugify(text.to_s.gsub("&", " and "), :mode => "default")
  end

  # anchor => { title:, group: } from the module's sidebar, plus group => [anchors]
  def sidebar(site, key)
    entries = Array(site.data.dig("navigation", "financetoolkit-docs-#{key}"))
    metrics = {}
    groups = Hash.new { |h, k| h[k] = [] }
    walk = lambda do |items, group|
      items.each do |item|
        url = item["url"].to_s
        if url.start_with?("#{DOCS_ROOT}/#{key}#get_")
          anchor = url.split("#", 2).last
          next if metrics.key?(anchor)
          metrics[anchor] = { :title => item["title"].to_s.strip, :group => group }
          groups[group] << anchor
        end
        walk.call(Array(item["children"]), item["title"].to_s.strip) if item["children"]
      end
    end
    walk.call(entries, MODULES[key])
    [metrics, groups]
  end

  # split a function section into its parts
  def parse(body)
    body = body.sub(/\n---\s*\z/, "").strip
    code_at   = body.index("```python")
    args_at   = body.index("**Args:**") || body.index("**Returns:**")
    desc_end  = [args_at, code_at, body.length].compact.min
    desc      = body[0...desc_end].strip
    args      = args_at ? body[args_at...(code_at || body.length)].sub(/\*\*As an example:\*\*\s*\z/, "").strip : ""
    example   = code_at ? body[code_at..].strip : ""
    { :description => desc, :arguments => args, :example => example }
  end

  def plain(markdown)
    markdown.gsub(/\$\$.*?\$\$/m, " ")
            .gsub(/\[([^\]]+)\]\([^)]+\)(\{:[^}]*\})?/, '\1')
            .gsub(/[*_`]/, "")
            .gsub(/\s+/, " ").strip
  end

  # First paragraph of the docstring, topped up with the next paragraphs when
  # it is a one-liner ("Calculate the Ljung-Box test for autocorrelation."),
  # and with a line about the page itself when even that stays short.
  def description_for(name, desc)
    paragraphs = desc.split(/\n\s*\n/)
                     .reject { |p| p.lstrip.start_with?("- ", "$$", "|") }
                     .map { |p| plain(p) }
                     .reject { |p| p.empty? || (p.end_with?(":") && p.length < 40) }
    text = paragraphs.shift.to_s
    text = "#{text} #{paragraphs.shift}" while text.length < 110 && !paragraphs.empty?
    text = "#{text} Formula, parameters and a Python example with the Finance Toolkit." if text.length < 110
    text = text.sub(/:\z/, ".")
    return text if text.length <= 158
    cut = text[0, 155]
    cut = cut[0, cut.rindex(" ") || cut.length].sub(/[,;:]\z/, "")
    "#{cut}..."
  end

  # The theme runs <title> through markdownify, where a bare "|" turns the
  # title into a table, so the separator is written as an entity (as the
  # theme's own title_separator is); lengths are measured with a plain "|".
  def seo_title_for(name)
    title = [
      "#{name}: Formula and Python Example | Finance Toolkit",
      "#{name}: Formula and Python Example",
      "#{name} in Python | Finance Toolkit",
      "#{name} in Python",
    ].find { |t| t.length <= 65 } || name
    title.sub(" | ", " &#124; ")
  end

  # just the argument bullets from the Args block, without Returns/Raises/Notes
  def arguments_for(block)
    args = block[/\*\*Args:\*\*\s*(.*?)(?=\*\*(?:Returns|Raises|Notes|As an example):\*\*|\z)/m, 1].to_s.strip
    args.start_with?("- ") ? args : ""
  end

  def content_for(name, key, fn_name, anchor, parts, related, module_url)
    module_name = MODULES[key]
    out = +""
    out << parts[:description] << "\n\n"
    unless parts[:example].empty?
      out << "## Calculate the #{name} in Python\n\n"
      out << "The #{name} is available in the #{module_name} module of the open-source "
      out << "[Finance Toolkit](/projects/financetoolkit). Install it with `pip install financetoolkit -U` "
      out << "and call `#{fn_name}` as shown below.\n\n"
      out << parts[:example] << "\n\n"
    end
    arguments = arguments_for(parts[:arguments])
    unless arguments.empty?
      out << "## Parameters\n\n"
      out << "`#{fn_name}` accepts the following parameters:\n\n"
      out << arguments << "\n\n"
    end
    # only a real sidebar group gives a meaningful "related" list; the modules
    # without groups would just list the rest of the module
    if !related.empty? && related.first[:group] != module_name
      out << "## Related #{related.first[:group]}\n\n"
      related.each { |r| out << "- [#{r[:title]}](#{r[:url]})\n" }
      out << "\n"
    end
    out << "The [#{module_name} module documentation](#{module_url}##{anchor}) lists every "
    out << "function of the module on a single page.\n"
    out
  end

  def unique_description(name, text, seen)
    unless seen.include?(text)
      seen << text
      return text
    end
    text = "#{name}: #{text}"
    text = "#{text[0, 155][0, text[0, 155].rindex(' ') || 155]}..." if text.length > 158
    seen << text
    text
  end

  def generate(site)
    seen_descriptions = []
    source_pages = site.pages.each_with_object({}) do |page, map|
      map[page.url] = page if page.url.start_with?(DOCS_ROOT)
    end

    MODULES.each_key do |key|
      module_url = "#{DOCS_ROOT}/#{key}"
      module_page = source_pages[module_url]
      next unless module_page

      metrics, groups = sidebar(site, key)
      # sidebar anchors are lowercase (kramdown's heading ids), a few function
      # names are not (get_EBT_to_EBIT), so sections are keyed by the lowercase
      # name and keep the real one for the code sample
      sections = module_page.content.scan(SECTION).to_h { |fn, body| [fn.downcase, [fn, body]] }

      urls = {}
      used = {}
      metrics.each do |anchor, info|
        next unless sections.key?(anchor)
        slug = slugify(info[:title])
        slug = "#{slug}-#{slugify(anchor.delete_prefix('get_'))}" if used[slug]
        used[slug] = true
        urls[anchor] = "#{module_url}/#{slug}"
      end

      urls.each do |anchor, url|
        info    = metrics[anchor]
        fn_name, body = sections[anchor]
        parts   = parse(body)
        related = groups[info[:group]].reject { |a| a == anchor || !urls[a] }.first(12).map do |a|
          { :title => metrics[a][:title], :url => urls[a], :group => info[:group] }
        end

        description = unique_description(info[:title], description_for(info[:title], parts[:description]), seen_descriptions)
        page = Page.new(site, site.source, url.delete_prefix("/").sub(%r{/[^/]+\z}, ""), "#{url.split('/').last}.md")
        page.content = content_for(info[:title], key, fn_name, anchor, parts, related, module_url)
        page.data.merge!(
          "layout"               => "single",
          "title"                => info[:title],
          "seo_title"            => seo_title_for(info[:title]),
          "seo_title_suffix"     => false,
          "description"          => description,
          "excerpt"              => description,
          "permalink"            => url,
          "classes"              => "wide-sidebar",
          "author_profile"       => false,
          "sidebar"              => { "nav" => "financetoolkit-docs-#{key}" },
          "redirect_from"        => ["#{url}/"],
          "docs_module"          => MODULES[key],
          "docs_function"        => fn_name,
          "last_modified_at"     => module_page.data["last_modified_at"],
          "last_modified_at_from_git" => module_page.data["last_modified_at_from_git"]
        )
        site.pages << page
        GENERATED << page.relative_path
      end

      # a small link under every function heading on the module page itself
      module_page.content = module_page.content.gsub(/^## (get_\w+)\n/) do
        fn = Regexp.last_match(1)
        anchor = fn.downcase
        next Regexp.last_match(0) unless urls[anchor]
        "## #{fn}\n<p class=\"docs-metric-link\"><a href=\"#{urls[anchor]}\">#{metrics[anchor][:title]}: formula, example and related metrics</a></p>\n\n"
      end
    end
  end

  class Generator < Jekyll::Generator
    safe true
    # before jekyll-redirect-from (normal) and jekyll-sitemap (lowest), so the
    # trailing-slash redirects and the sitemap entries include these pages
    priority :high

    def generate(site)
      GENERATED.clear
      DocsMetricPages.generate(site)
    end
  end
end

# Keep the generated pages out of the Algolia index; the module pages hold the
# same text and search results should point there, not show every hit twice.
# (This site defines no other Algolia hooks; move them here if that changes.)
if defined?(Jekyll::Algolia::Hooks)
  module Jekyll
    module Algolia
      module Hooks
        def self.should_be_excluded?(filepath)
          DocsMetricPages::GENERATED.any? { |path| filepath.to_s.end_with?(path) }
        end

        # the "formula, example and related metrics" links on the module pages
        # are navigation, not content worth a search result of their own
        def self.before_indexing_each(record, node, _context)
          return nil if node.respond_to?(:[]) && node["class"].to_s.split.include?("docs-metric-link")
          record
        end
      end
    end
  end
end
